/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include "e_mscryptpfx_err.h"

#ifndef OPENSSL_NO_ERR

static ERR_STRING_DATA MSCRYPTPFX_str_functs[] = {
    {ERR_PACK(0, MSCRYPTPFX_F_CTRL, 0), "mscryptpfx_ctrl"},
    {ERR_PACK(0, MSCRYPTPFX_F_CTX_NEW, 0), "mscryptpfx_ctx_new"},
    {ERR_PACK(0, MSCRYPTPFX_F_INIT, 0), "mscryptpfx_init"},
    {ERR_PACK(0, MSCRYPTPFX_F_LOAD, 0), "mscryptpfx_load"},
    {ERR_PACK(0, MSCRYPTPFX_F_RSA_PRIV_DEC, 0), "mscryptpfx_rsa_priv_dec"},
    {ERR_PACK(0, MSCRYPTPFX_F_RSA_PRIV_ENC, 0), "mscryptpfx_rsa_priv_enc"},
    {ERR_PACK(0, MSCRYPTPFX_F_GET_PRIVATE_RSA, 0), "mscryptpfx_get_private_rsa"},
    {ERR_PACK(0, MSCRYPTPFX_F_GET_PRIVATE_EC_KEY, 0), "mscryptpfx_get_private_eckey"},
    {ERR_PACK(0, MSCRYPTPFX_F_EC_KEY_SIGN, 0), "mscryptpfx_eckey_sign"},
    {ERR_PACK(0, MSCRYPTPFX_F_EC_KEY_SIGN_SETUP, 0), "mscryptpfx_eckey_sign_setup"},
    {ERR_PACK(0, MSCRYPTPFX_F_EC_KEY_SIGN_SIG, 0), "mscryptpfx_eckey_sign_sig"},
    {ERR_PACK(0, MSCRYPTPFX_F_VTRACE, 0), "mscryptpfx_vtrace"},
    {0, NULL}
};


static ERR_STRING_DATA MSCRYPTPFX_str_reasons[] = {
    {ERR_PACK(0, 0, MSCRYPTPFX_R_ALLOC_FAILURE), "allocation failure"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_CANT_FIND_MSCRYPTPFX_CONTEXT), "cant find mscryptpfx context"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_PARSE_PFX_KEY_ID_ERROR), "parse keyId error"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_LOAD_PFX_PUBKEY_ERROR), "load pfx public key error"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_PFX_OPEN_ERROR), "pfx open error"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_UNSUPPORTED_SSL_CLIENT_CERT), "unsupported ssl client cert"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_CANT_GET_KEY), "cant get key"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_CANT_GET_METHOD), "cant get methid"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_ENGINE_NOT_INITIALIZED), "engine not initialized"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_FILE_OPEN_ERROR), "file open error"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_INVALID_RSA), "invalid RSA"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_INVALID_EC_KEY), "invalid EC_KEY"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_UNSUPPORTED_KEY_ALGORITHM), "unsupported key algorithm"},
    {ERR_PACK(0, 0, MSCRYPTPFX_R_UNKNOWN_COMMAND), "unknown command"},
    {0, NULL}
};

#endif

static int lib_code = 0;
static int error_loaded = 0;

static int ERR_load_MSCRYPTPFX_strings(void)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();

    if (!error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(lib_code, MSCRYPTPFX_str_functs);
        ERR_load_strings(lib_code, MSCRYPTPFX_str_reasons);
#endif
        error_loaded = 1;
    }
    return 1;
}

static void ERR_unload_MSCRYPTPFX_strings(void)
{
    if (error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(lib_code, MSCRYPTPFX_str_functs);
        ERR_unload_strings(lib_code, MSCRYPTPFX_str_reasons);
#endif
        error_loaded = 0;
    }
}

static void ERR_MSCRYPTPFX_error(int function, int reason, char *file, int line)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();
    ERR_PUT_error(lib_code, function, reason, file, line);
}
