/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_MSCRYPTPFXERR_H
# define HEADER_MSCRYPTPFXERR_H

# define MSCRYPTPFXerr(f, r) ERR_MSCRYPTPFX_error((f), (r), __FILE__, __LINE__)


/*
 * MSCRYPTPFX function codes.
 */
# define MSCRYPTPFX_F_CTRL                              0x100
# define MSCRYPTPFX_F_CTX_NEW                           0x101
# define MSCRYPTPFX_F_INIT                              0x102
# define MSCRYPTPFX_F_LOAD                              0x103
# define MSCRYPTPFX_F_RSA_PRIV_DEC                      0x104
# define MSCRYPTPFX_F_RSA_PRIV_ENC                      0x105
# define MSCRYPTPFX_F_GET_PRIVATE_RSA                   0x106
# define MSCRYPTPFX_F_GET_PRIVATE_EC_KEY                0x107
# define MSCRYPTPFX_F_EC_KEY_SIGN                       0x108
# define MSCRYPTPFX_F_EC_KEY_SIGN_SETUP                 0x109
# define MSCRYPTPFX_F_EC_KEY_SIGN_SIG                   0x10A
# define MSCRYPTPFX_F_VTRACE                            0x10B

/*
 * MSCRYPTPFX reason codes.
 */
# define MSCRYPTPFX_R_ALLOC_FAILURE                     0x100
# define MSCRYPTPFX_R_CANT_FIND_MSCRYPTPFX_CONTEXT      0x101
# define MSCRYPTPFX_R_PARSE_PFX_KEY_ID_ERROR            0x102
# define MSCRYPTPFX_R_LOAD_PFX_PUBKEY_ERROR             0x103
# define MSCRYPTPFX_R_PFX_OPEN_ERROR                    0x104
# define MSCRYPTPFX_R_UNSUPPORTED_SSL_CLIENT_CERT       0x105
# define MSCRYPTPFX_R_CANT_GET_KEY                      0x106
# define MSCRYPTPFX_R_CANT_GET_METHOD                   0x107
# define MSCRYPTPFX_R_ENGINE_NOT_INITIALIZED            0x108
# define MSCRYPTPFX_R_FILE_OPEN_ERROR                   0x109
# define MSCRYPTPFX_R_INVALID_RSA                       0x10A
# define MSCRYPTPFX_R_INVALID_EC_KEY                    0x10B
# define MSCRYPTPFX_R_UNSUPPORTED_KEY_ALGORITHM         0x10C
# define MSCRYPTPFX_R_UNKNOWN_COMMAND                   0x10D



#endif
